### PR TITLE
chore: switch exposed kvrock client to interface

### PR DESCRIPTION
**Pull request by jaanzhang**
**Changes**

- Construct kvrock client as a interface, which shall be easier to mock for future tests.
- Rename `sigs.k8s.io/controller-runtime/pkg/client` to `k8sApiClient` to avoid confusion.
- Add necessary comments to kvrock client methods.

### CODE REVIEW

**Comment by jiayouxujin** [comment]
Hi, @jiayinzhang-mint 
I noticed that your PR has some conflicts with the base branch. Could you please rebase it to resolve these issues?

**Comment by jaanzhang** [comment]
> Hi, @jiayinzhang-mint I noticed that your PR has some conflicts with the base branch. Could you please rebase it to resolve these issues?

Done.

**Review by jiayouxujin — APPROVED** [review]
LGTM.

**Comment by jaanzhang** [comment]
https://github.com/helm/chart-testing-action/issues/132

**Pull request merged**
